### ISSUE TITLE
REQUEST FEATURES: SPECIFIC-TOPICS DOWNLOADER

### ISSUE THREAD

**Issue by hungphongtrn** [VikParuchuri/libgen_to_txt#1]
Thank you for you amazing work! I would love to request for a feature to download for a specific set of keywords on LibGen!

**Comment by VikParuchuri** [comment]
This wouldn't be super hard to implement:

- Select the right md5 hashes from the metadata db based on keyword/topic
- Lookup which chunks those hashes are in
- Download only those chunks, and only the files you want

I don't have time to work on this, but welcome PRs if anyone is interested.
